---
layout: post
codemirror: true
categories: [Python, Mathematical-Expressions]
lesson_language: Python
lesson_topic: Mathematical-Expressions
lesson_part: interactive
lesson_type: lesson
title: 3.3 Math Expressions HW
permalink: /csp/python/math-expressions/hw
Authors: Samanvi Yachareni
---

## Popcorn Hack 1

Prediction: total 135, difference 90, product 250, quotient 10.0. `/` produces a floating-point quotient.

In [1]:
# CODE_RUNNER: Math Expressions - practice 2

value_a = 100
value_b = 10
value_c = 25

addition = value_a + value_b + value_c
subtraction = value_a - value_b
multiplication = value_b * value_c
division = value_a / value_b

print("Total:", addition)
print("Difference:", subtraction)
print("Product:", multiplication)
print("Division:", division)

Total: 135
Difference: 90
Product: 250
Division: 10.0


### Recorded output

<pre>Total: 135
Difference: 90
Product: 250
Division: 10.0</pre>

## Popcorn Hack 2

Prediction: 12 spots booked, 88 left, and 44.0 per room. Multiplication happens before subtraction.

In [2]:
# CODE_RUNNER: Math Expressions - practice 4

total_monthly_capacity = 100
spots_requested_per_group = 4
sessions_booked = 3

total_spots_taken = spots_requested_per_group * sessions_booked
remaining_capacity = total_monthly_capacity - total_spots_taken
users_per_room = remaining_capacity / 2

print("Total Spots Taken:", total_spots_taken)
print("Remaining Capacity:", remaining_capacity)
print("Users per Room:", users_per_room)

Total Spots Taken: 12
Remaining Capacity: 88
Users per Room: 44.0


### Recorded output

<pre>Total Spots Taken: 12
Remaining Capacity: 88
Users per Room: 44.0</pre>

### Weekly and monthly session costs

The lesson also requests weekly and monthly costs in Popcorn 2. Prediction: $105 per week and $420 per four-week month.

In [3]:
# CODE_RUNNER: Popcorn 2 - session costs

cost_per_session = 35
sessions_per_week = 3
weeks_per_month = 4
weekly_cost = cost_per_session * sessions_per_week
monthly_cost = weekly_cost * weeks_per_month
print("Weekly Cost:", weekly_cost)
print("Monthly Cost:", monthly_cost)
assert (weekly_cost, monthly_cost) == (105, 420)


Weekly Cost: 105
Monthly Cost: 420


### Recorded output

<pre>Weekly Cost: 105
Monthly Cost: 420</pre>

## Homework Hack

In [4]:
# CODE_RUNNER: Math Expressions - practice 6

cost_per_session = 35
sessions_per_week = 3
weeks_per_month = 4
enrollment_fee = 75

weekly_cost = cost_per_session * sessions_per_week
monthly_cost = weekly_cost * weeks_per_month
total_cost_with_fee = monthly_cost + enrollment_fee
average_daily_cost = monthly_cost / 30

print("Weekly Cost:", weekly_cost)
print("Monthly Cost:", monthly_cost)
print("Total Cost with Fee:", total_cost_with_fee)
print("Average Daily Cost:", average_daily_cost)

Weekly Cost: 105
Monthly Cost: 420
Total Cost with Fee: 495
Average Daily Cost: 14.0


### Recorded output

<pre>Weekly Cost: 105
Monthly Cost: 420
Total Cost with Fee: 495
Average Daily Cost: 14.0</pre>

## Lesson reference

[Official requirements](https://pages.opencodingsociety.com/csp/python/math-expressions/lesson) · [All Python homework]({{site.baseurl}}/homework/)

## Explanation and tests

The first-month fee is added once. The daily average uses the monthly session cost, without the enrollment fee. Expected homework results: 105, 420, 495, 14.0. The lesson URL currently returns 404 directly; the indexed official lesson was used to verify its requirements.

In [5]:
# CODE_RUNNER: Explanation and tests

def cost_report(price, sessions, weeks, fee):
    weekly = price * sessions
    monthly = weekly * weeks
    return weekly, monthly, monthly + fee, monthly / 30
for inputs, expected in [((35, 3, 4, 75), (105, 420, 495, 14.0)),
                         ((35, 0, 4, 75), (0, 0, 75, 0.0)),
                         ((20, 2, 4, 0), (40, 160, 160, 160 / 30))]:
    actual = cost_report(*inputs)
    assert actual == expected
    print(inputs, "->", actual)


(35, 3, 4, 75) -> (105, 420, 495, 14.0)
(35, 0, 4, 75) -> (0, 0, 75, 0.0)
(20, 2, 4, 0) -> (40, 160, 160, 5.333333333333333)


### Recorded output

<pre>(35, 3, 4, 75) -&gt; (105, 420, 495, 14.0)
(35, 0, 4, 75) -&gt; (0, 0, 75, 0.0)
(20, 2, 4, 0) -&gt; (40, 160, 160, 5.333333333333333)</pre>